#!/bin/sh
# -*- mode:sh -*-

CONF_DIR=$HOME/.config/i3
HOSTNAME=$(hostname)

${CONF_DIR}/scripts/build_config.sh

ln -sf $HOME/.config/i3blocks/config.`hostname` $HOME/.config/i3blocks/i3blocks.conf

exec /usr/bin/i3
